// const quotes = [
//   "Be yourself; everyone else is already taken.",
//   "To live is the rarest thing in the world. Most people exist, that is all.",
//   "True friends stab you in the front.",
//   "Women are made to be Loved, not understood.",
//   "Be the change that you wish to see in the world.",
//   "Live as if you were to die tomorrow. Learn as if you were to live forever.",
//   "No one can make you feel inferior without your consent.",
//   "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
//   "Do what you feel in your heart to be right - for you'll be criticized anyway.",
//   "Do one thing every day that scares you.",
//   "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate; only love can do that.",
//   "Our lives begin to end the day we become silent about things that matter.",
//   "In the end, we will remember not the words of our enemies, but the silence of our friends.",
//   "Injustice anywhere is a threat to justice everywhere.",
//   "The time is always right to do what is right.",
//   "Life's most persistent and urgent question is, 'What are you doing for others?",
//   "Weak people revenge. Strong people forgive. Intelligent People Ignore.",
//   "I have not failed. I've just found 10,000 ways that won't work.",
//   "Genius is one percent inspiration and ninety-nine percent perspiration.",
//   "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
//   "If we did all the things we are capable of, we would literally astound ourselves.",
//   "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
//   "Life isn't about finding yourself. Life is about creating yourself.",
//   "Success is not final, failure is not fatal: it is the courage to continue that counts.",
//   "If you're going through hell, keep going.",
//   "We make a living by what we get, but we make a life by what we give.",
//   "Peace begins with a smile.",
//   "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
//   "If you can't feed a hundred people, then feed just one.",
//   "Kind words can be short and easy to speak, but their echoes are truly endless.",
//   "Isn't it nice to think that tomorrow is a new day with no mistakes in it yet?",
//   "It's so easy to be wicked without knowing it, isn't it?",
//   "All the darkness in the world cannot extinguish the light of a single candle.",
//   "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
//   "Preach the Gospel at all times and when necessary use words.",
//   "A single sunbeam is enough to drive away many shadows.",
//   "You never fail until you stop trying.",
//   "You see things; you say, 'Why?' But I dream things that never were; and I say 'Why not?",
//   "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
//   "The two most important days in your life are the day you are born and the day you find out why.",
//   "Truth is stranger than fiction, but it is because Fiction is obliged to stick to possibilities; Truth isn't.",
//   "If you tell the truth, you don't have to remember anything.",
//   "I have never met a man so ignorant that I couldn't learn something from him",
//   "Where there is love there is life.",
//   "Happiness is when what you think, what you say, and what you do are in harmony.",
//   "The weak can never forgive. Forgiveness is the attribute of the strong.",
//   "Strength does not come from physical capacity. It comes from an indomitable will.",
//   "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty",
//   "In a gentle way, you can shake the world.",
//   "He that can have patience can have what he will.",
//   "Either write something worth reading or do something worth writing.",
//   "Tell me and I forget, teach me and I may remember, involve me and I learn.",
//   "Never ruin an apology with an excuse.",
//   "Early to bed and early to rise makes a man healthy, wealthy and wise.",
//   "By failing to prepare, you are preparing to fail.",
//   "Those who look for the bad in people will surely find it.",
//   "People don't realize how a man's whole life can be changed by one book.",
//   "If you have no critics you'll likely have no success.",
//   "I'm for truth, no matter who tells it. I'm for justice, no matter who it's for or against.",
//   "It is not a lack of Love, but a lack of People that makes unhappy marriages.",
//   "He who has a why to live can bear almost any how.",
//   "That which does not kill us makes us stronger",
//   "To live is to suffer, to survive is to find some meaning in the suffering.",
//   "There is always some madness in love. But there is also always some reason in madness.",
//   "No price is too high to pay for the privilege of owning yourself.",
//   "You know, when it works, Love is amazing. It's not overrated.",
//   "Life is an awful, ugly place to not have a best friend.",
//   "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.",
//   "Anyone can hide. Facing up to things, working through them, that's what makes you strong.",
//   "If you want to live a happy life, tie it to a goal, not to people or things",
//   "Your time is limited, so don't waste it living someone else's life.",
//   "Everything around you that you call life was made up by people, and you can change it.",
//   "Design is not just what it looks like and feels like. Design is how it works.",
//   "Innovation distinguishes between a leader and a follower.",
//   "Sometimes life is going to hit you in the head with a brick. Don't lose faith.",
//   "Sometimes when you innovate, you make mistakes. It is best to admit them quickly, and get on with improving your other innovations",
//   "A lot of times, people don't know what they want until you show it to them.",
//   "Let's go invent tomorrow rather than worrying about what happened yesterday.",
//   "The most precious thing that we all have with us is time.",
//   "You have to trust in something, your gut, destiny, life, karma, whatever.",
//   "Every child is an artist, the problem is staying an artist when you grow up.",
//   "The purpose of art is washing the dust of daily life off our souls.",
//   "Good artists copy, great artists steal.",
//   "Strive not to be a success, but rather to be of value.",
//   "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
//   "We learn wisdom from failure much more than from succes.",
//   "Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.",
//   "We often discover what will do, by finding out what will not do; and probably he who never made a mistake never made a discovery.",
//   "Lost wealth may be replaced by industry, lost knowledge by study, lost health by temperance or medicine, but lost time is gone forever.",
//   "Life will always be to a large extent what we ourselves make it.",
//   "Enthusiasm... the sustaining power of all great action.",
//   "People who are crazy enough to think they can change the world, are the ones who do.",
//   "The fool doth think he is wise, but the wise man knows himself to be a fool.",
//   "Expectation is the root of all heartache.",
//   "Listen to many, speak to a few.",
//   "One may smile, and smile, and be a villain.",
//   "Any fool can know. The point is to understand.",
//   "It is not that I'm so smart. But I stay with the questions much longer.",
//   "Build your own dreams, or someone else will hire you to build theirs.",
//   "Comfort is the enemy of achievement",
//   "You know, you don't have to have money to be a successful businessperson.",
//   "I can dream alone and strive alone, but true success always requires the help and support of others.",
//   "Success isn't something that happens overnight: it's a process.",
//   "The more we give, the more we receive. It's important to give back, because the seeds you plant today, you will harvest tomorrow.",
//   "Start from wherever you are and with whatever you've got.",
//   "Without constant activity, the threats of life will soon overwhelm the values",
//   "If you don't like how things are, change it! You're not a tree.",
//   "Success is neither magical nor mysterious. Success is the natural consequence of consistently applying basic fundamentals.",
//   "How long should you try? Until.",
//   "Focus on making yourself better, not on thinking that you are better.",
//   "Knowledge is like underwear. It is useful to have it, but not necessary to show it off.",
//   "You can change your world by changing your words... Remember, death and life are in the power of the tongue.",
//   "Nothing is impossible, the word itself says 'I'm possible'!",
//   "As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others.",
//   "I never think of myself as an icon. What is in other people's minds is not in my mind. I just do my thing.",
//   "The best thing to hold onto in life is each other.",
//   "Be nice to nerds. Chances are you'll end up working for one.",
//   "Your most unhappy customers are your greatest source of learning.",
//   "Success is a lousy teacher. It seduces smart people into thinking they can't lose.",
//   "Life is not fair; get used to it.",
//   "If you can't make it good, at least make it look good.",
//   "Life is like riding a bicycle. To keep your balance, you must keep moving.",
//   "Nearly all men can stand adversity, but if you want to test a man’s character, give him power.",
//   "The best way to predict your future is to create it.",
//   "I would rather be a little nobody, then to be a evil somebody.",
//   "I will prepare and some day my chance will come.",
//   "Important principles may, and must, be inflexible.",
//   "Tact is the ability to describe others as they see themselves.",
//   "You cannot escape the responsibility of tomorrow by evading it today.",
//   "Knowing thyself, that is the greatest wisdom.",
//   "To be humane, we must ever be ready to pronounce that wise, ingenious and modest statement 'I do not know'.",
//   "Two truths cannot contradict one another.",
//   "Where the senses fail us, reason must step in.",
//   "All truths are easy to understand once they are discovered; the point is to discover them.",
// ];
const quotes = [
  "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end. Aristotle",
  "If the wind will not serve, take to the oars. Latin Proverb",
  "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground. Unknown",
  "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. Marie Curie",
  "Too many of us are not living our dreams because we are living our fears. Les Brown",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. Joshua J. Marine",
  "If you want to lift yourself up, lift up someone else. Booker T. Washington",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. Leonardo da Vinci",
  "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless. Jamie Paolinetti",
  "You take your life in your own hands, and what happens? A terrible thing, no one to blame. Erica Jong",
  "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. Bob Dylan",
  "I didn’t fail the test. I just found 100 ways to do it wrong. Benjamin Franklin",
  "In order to succeed, your desire for success should be greater than your fear of failure. Bill Cosby",
  "A person who never made a mistake never tried anything new.  Albert Einstein",
  "The person who says it cannot be done should not interrupt the person who is doing it. Chinese Proverb",
  "There are no traffic jams along the extra mile. Roger Staubach",
  "It is never too late to be what you might have been. George Eliot",
  "You become what you believe. Oprah Winfrey",
  "I would rather die of passion than of boredom. Vincent van Gogh",
  "A truly rich man is one whose children run into his arms when his hands are empty. Unknown",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings. Ann Landers",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money. Abigail Van Buren",
  "Build your own dreams, or someone else will hire you to build theirs. Farrah Gray",
  "The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at. Jesse Owens",
  "Education costs money.  But then so does ignorance. Sir Claus Moser",
  "I have learned over the years that when one’s mind is made up, this diminishes fear. Rosa Parks",
  "It does not matter how slowly you go as long as you do not stop. Confucius",
  "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough. Oprah Winfrey",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck. Dalai Lama",
  "You can’t use up creativity.  The more you use, the more you have. Maya Angelou",
  "Dream big and dare to fail. Norman Vaughan",
  "Our lives begin to end the day we become silent about things that matter. Martin Luther King Jr.",
  "Do what you can, where you are, with what you have. Teddy Roosevelt",
  "If you do what you’ve always done, you’ll get what you’ve always gotten. Tony Robbins",
  "Dreaming, after all, is a form of planning. Gloria Steinem",
  "It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live. Mae Jemison",
  "You may be disappointed if you fail, but you are doomed if you don’t try. Beverly Sills",
  "Remember no one can make you feel inferior without your consent. Eleanor Roosevelt",
  "Life is what we make it, always has been, always will be. Grandma Moses",
  "The question isn’t who is going to let me; it’s who is going to stop me. Ayn Rand",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. Henry Ford",
  "It’s not the years in your life that count. It’s the life in your years. Abraham Lincoln",
  "Change your thoughts and you change your world. Norman Vincent Peale",
  "Either write something worth reading or do something worth writing. Benjamin Franklin",
  "Nothing is impossible, the word itself says, “I’m possible!” –Audrey Hepburn",
  "The only way to do great work is to love what you do. Steve Jobs",
  "If you can dream it, you can achieve it. Zig Ziglar",
];

const generateButton = document.getElementById("generateButton");
const quoteDisplay = document.getElementById("quoteDisplay");
function generateQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  const quote = quotes[randomIndex];
  quoteDisplay.innerText = quote;
}

generateButton.addEventListener("click", generateQuote);
